# -*- coding: utf-8 -*-
#对计算机说使用以下代码使用utf-8编码
# Form implementation generated from reading ui file 'D:\texePyQt5\layoutWin.ui'
#读取ui文件'D:\texePyQt5\layoutWin.ui'生成窗口实现
# Created by: PyQt5 UI code generator 5.15.4
#创造者:PyQt5 UI代码生成器5.15.4
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
#警告:当pyuic5启动时，对该文件所做的任何手动更改将丢失
# run again.  Do not edit this file unless you know what you are doing.
#再次运行。除非您知道自己在做什么，否则不要编辑这个文件。
#上面的话是对查看代码的程序员说的

from PyQt5 import QtCore, QtGui, QtWidgets
#从PyQt5 引入QtCore, QtGui, QtWidgets类
#QtCore是Qt的核心内容，也是最基本的模块是运行的基础
#QtGui是图形用户界面的基础
#QtWidgets类是对界面元素的设定
class Ui_Dialog(object):
#新建一个object的子类Ui_Dialog
#在python3.x的所有类都是object的子类
    def setupUi(self, Dialog):
    #设一个setupUi函数
        Dialog.setObjectName("Dialog")
        #设置对象名字为Dialog
        Dialog.resize(547, 623)
        #调整对象Dialog大小
        Dialog.setSizeGripEnabled(True)
        #将Dialog对象尺寸控制为真
        self.widget = QtWidgets.QWidget(Dialog)
        #将QtWidgets.QWidget的对象Dialog赋值给self.widget 
        self.widget.setGeometry(QtCore.QRect(20, 30, 167, 101))
        #设定按钮quit位置尺寸为QtCore.QRect的对象20, 30, 167, 101
        #QtCore.QRect是用来构造一个空的矩形的类
        self.widget.setObjectName("widget")
         #设置self.widget对象名字为widget
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        #将QtWidgets.QVBoxLayout的对象self.widget赋值给self.verticalLayout_2
        #QtWidgets.QVBoxLayout是将小部件进行垂直的类
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        #将self.verticalLayout_2的小部件内容周围的边距设置为0, 0, 0, 0
        #setContentsMargins是设置小部件内容周围的边距的函数
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #设置self.verticalLayout_2对象名字为verticalLayout_2
        self.label = QtWidgets.QLabel(self.widget)
         #将QtWidgets.QLabel的对象self.widget赋值给self.label
         #QLabel是构造一个标签的类
        self.label.setObjectName("label")
        #设置self.label对象名字为label
        self.verticalLayout_2.addWidget(self.label)
        #将self.verticalLayout_2增加的小部件self.label
        self.horizontalLayout = QtWidgets.QHBoxLayout()
         #将QtWidgets.QHBoxLayout的默认对象赋值给self.horizontalLayout
         #QHBoxLayou是水平排列小部件的类
        self.horizontalLayout.setObjectName("horizontalLayout")
        #设置elf.horizontalLayout对象名字为horizontalLayout
        self.label_2 = QtWidgets.QLabel(self.widget)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label_2
        self.label_2.setObjectName("label_2")
        #设置self.label_2对象名字为label_2
        self.horizontalLayout.addWidget(self.label_2)
        #将self.verticalLayout增加的小部件设为self.label_2
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        #将QtWidgetsQLineEdit的对象self.widget赋值给self.lineEdit
        #QLineEdit是构建行编辑的类
        self.lineEdit.setObjectName("lineEdit")
        #设置self.lineEdit对象名字为lineEdit
        self.horizontalLayout.addWidget(self.lineEdit)
        #将self.verticalLayout增加的小部件self.lineEdit
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        #将self.verticalLayout_2增加的小部件self.horizontalLayout
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QHBoxLayou的默认对象赋值给self.horizontalLayout_2
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        #设置self.horizontalLayout_2对象名字为horizontalLayout_2
        self.label_3 = QtWidgets.QLabel(self.widget)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label_3
        self.label_3.setObjectName("label_3")
        #设置self.label_3对象名字为label_3
        self.horizontalLayout_2.addWidget(self.label_3)
        #将self.verticalLayout_2增加的小部件self.label_3
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        #将QtWidgets.QLineEdit的对象self.widget赋值给self.lineEdit_2
        self.lineEdit_2.setObjectName("lineEdit_2")
        #设置self.lineEdit_2对象名字为lineEdit_2
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        #将self.verticalLayout_2增加的小部件self.lineEdit_2
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        #将self.verticalLayout_2增加的小部件self.horizontalLayout_2
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QHBoxLayout的默认对象赋值给self.horizontalLayout_3
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        #设置self.horizontalLayout_3对象名字为horizontalLayout_3
        self.pushButton = QtWidgets.QPushButton(self.widget)
        #将QtWidgets.QPushButton的对象self.widget赋值给self.pushButton
        self.pushButton.setObjectName("pushButton")
        #设置self.pushButton对象名字为pushButton
        self.horizontalLayout_3.addWidget(self.pushButton)
        #将self.verticalLayout_3增加的小部件设为self.pushButton
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        #将QtWidgets.QPushButton的对象self.widget赋值给self.pushButton_2
        self.pushButton_2.setObjectName("pushButton_2")
        #设置self.pushButton_2对象名字为pushButton_2
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        #将self.horizontalLayout_3增加的小部件设为self.pushButton_2
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        #将self.verticalLayout_2增加的布局设为self.self.horizontalLayout_3
        self.widget1 = QtWidgets.QWidget(Dialog)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.widget1.setGeometry(QtCore.QRect(330, 10, 191, 223))
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.widget1.setObjectName("widget1")
        #设置self.widget1对象名字为widget1
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        #设置self.verticalLayout_3对象名字为verticalLayout_3
        self.label_4 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_4.setObjectName("label_4")
        #设置self.label_4对象名字为label_4
        self.verticalLayout_3.addWidget(self.label_4)
        #将self.verticalLayout_3增加的小部件设为self.label_4
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        #设置self.horizontalLayout_4对象名字为horizontalLayout_4
        self.label_5 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_5.setObjectName("label_5")
        #设置self.label_5对象名字为label_5
        self.horizontalLayout_4.addWidget(self.label_5)
        #将self.verticalLayout_4增加的小部件设为self.label_5
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.lineEdit_6.setObjectName("lineEdit_6")
        #设置self.lineEdit_6对象名字为lineEdit_6
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        #将self.horizontalLayout_4增加的小部件设为self.lineEdit_6
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        #将self.verticalLayout_3增加的布局设为self.horizontalLayout_4
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        #设置self.horizontalLayout_5对象名字为horizontalLayout_5
        self.label_9 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_9.setObjectName("label_9")
        #设置self.label_9对象名字为label_9
        self.horizontalLayout_5.addWidget(self.label_9)
        #将self.horizontalLayout_5增加的小部件设为self.label_9
        self.radioButton = QtWidgets.QRadioButton(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.radioButton.setObjectName("radioButton")
        #设置self.radioButton对象名字为radioButton
        self.horizontalLayout_5.addWidget(self.radioButton)
        #将self.horizontalLayout_5增加的小部件设为self.radioButton
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.radioButton_2.setObjectName("radioButton_2")
        #设置self.radioButton_2对象名字为radioButton_2
        self.horizontalLayout_5.addWidget(self.radioButton_2)
        #将self.horizontalLayout_5增加的小部件设为self.radioButton_2
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        #设置self.horizontalLayout_6对象名字为horizontalLayout_6
        self.label_6 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_6.setObjectName("label_6")
        #设置self.label_6对象名字为label_6
        self.horizontalLayout_6.addWidget(self.label_6)
        #将self.horizontalLayout_6增加的小部件设为self.label_6
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.lineEdit_3.setObjectName("lineEdit_3")
        #设置self.lineEdit_3对象名字为lineEdit_3
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        #设置self.horizontalLayout_7对象名字为horizontalLayout_7
        self.label_7 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_7.setObjectName("label_7")
        #设置self.label_7对象名字为label_7
        self.horizontalLayout_7.addWidget(self.label_7)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.lineEdit_4.setObjectName("lineEdit_4")
        #设置self.lineEdit_4对象名字为lineEdit_4
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        #设置self.horizontalLayout_8对象名字为horizontalLayout_8
        self.label_8 = QtWidgets.QLabel(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.label_8.setObjectName("label_8")
        #设置self.label_8对象名字为label_8
        self.horizontalLayout_8.addWidget(self.label_8)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.lineEdit_5.setObjectName("lineEdit_5")
        #设置self.lineEdit_5对象名字为lineEdit_5
        self.horizontalLayout_8.addWidget(self.lineEdit_5)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.checkBox_2.setObjectName("checkBox_2")
        #设置self.checkBox_2对象名字为checkBox_2
        self.verticalLayout_3.addWidget(self.checkBox_2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.checkBox.setObjectName("checkBox")
        #设置self.checkBox对象名字为checkBox
        self.verticalLayout_3.addWidget(self.checkBox)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_3.setObjectName("pushButton_3")
        #设置self.pushButton_3对象名字为pushButton_3
        self.verticalLayout_3.addWidget(self.pushButton_3)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.widget2 = QtWidgets.QWidget(Dialog)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.widget2.setGeometry(QtCore.QRect(30, 290, 321, 147))
        #将self.verticalLayout_2增加的小部件设为self.label
        self.widget2.setObjectName("widget2")
        #设置self.widget2对象名字为widget2
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        #设置self.verticalLayout_4对象名字为verticalLayout_4
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        #设置self.horizontalLayout_9对象名字为horizontalLayout_9
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.lineEdit_7.setObjectName("lineEdit_7")
        #设置self.lineEdit_7对象名字为lineEdit_7
        self.horizontalLayout_9.addWidget(self.lineEdit_7)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_17 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_17.setObjectName("pushButton_17")
        #设置self.pushButton_17对象名字为pushButton_17
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        #设置self.horizontalLayout_10对象名字为horizontalLayout_10
        self.gridLayout = QtWidgets.QGridLayout()
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.gridLayout.setObjectName("gridLayout")
        #设置self.gridLayout对象名字为gridLayout
        self.pushButton_12 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_12.setObjectName("pushButton_12")
        #设置self.pushButton_12对象名字为pushButton_12
        self.gridLayout.addWidget(self.pushButton_12, 3, 0, 1, 1)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_4 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_4.setObjectName("pushButton_4")
        #设置self.pushButton_4对象名字为pushButton_4
        self.gridLayout.addWidget(self.pushButton_4, 0, 0, 1, 1)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_5 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_5.setObjectName("pushButton_5")
        #设置self.pushButton_5对象名字为pushButton_5
        self.gridLayout.addWidget(self.pushButton_5, 0, 1, 1, 3)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_10 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_10.setObjectName("pushButton_10")
        #设置self.pushButton_10对象名字为pushButton_10
        self.gridLayout.addWidget(self.pushButton_10, 1, 4, 2, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_6 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_6.setObjectName("pushButton_6")
        #设置self.pushButton_6对象名字为pushButton_6
        self.gridLayout.addWidget(self.pushButton_6, 0, 4, 1, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_7 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_7.setObjectName("pushButton_7")
        #设置self.pushButton_7对象名字为pushButton_7
        self.gridLayout.addWidget(self.pushButton_7, 0, 6, 1, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_9.setObjectName("pushButton_9")
        #设置self.pushButton_9对象名字为pushButton_9
        self.gridLayout.addWidget(self.pushButton_9, 1, 1, 2, 3)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_16 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_16.setObjectName("pushButton_16")
        #设置self.pushButton_16对象名字为pushButton_16
        self.gridLayout.addWidget(self.pushButton_16, 4, 0, 1, 6)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_11 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_11.setObjectName("pushButton_11")
        #设置self.pushButton_11对象名字为pushButton_11
        self.gridLayout.addWidget(self.pushButton_11, 1, 6, 2, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_8 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_8.setObjectName("pushButton_8")
        #设置self.pushButton_8对象名字为pushButton_8
        self.gridLayout.addWidget(self.pushButton_8, 1, 0, 2, 1)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_14 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_14.setObjectName("pushButton_14")
        #设置self.pushButton_14对象名字为pushButton_14
        self.gridLayout.addWidget(self.pushButton_14, 3, 4, 1, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_15 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_15.setObjectName("pushButton_15")
        #设置self.pushButton_15对象名字为pushButton_15
        self.gridLayout.addWidget(self.pushButton_15, 3, 6, 1, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_19 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_19.setObjectName("pushButton_19")
        #设置self.pushButton_19对象名字为pushButton_19
        self.gridLayout.addWidget(self.pushButton_19, 4, 6, 1, 2)
        #将self.verticalLayout_2增加的小部件设为self.label
        self.pushButton_13 = QtWidgets.QPushButton(self.widget2)
        #将QtWidgets.QLabel的对象self.widget赋值给self.label
        self.pushButton_13.setObjectName("pushButton_13")
        #设置self.pushButton_13对象名字为pushButton_13
        self.gridLayout.addWidget(self.pushButton_13, 3, 1, 1, 3)
        #将self.gridLayout增加窗口设为self.pushButton_13, 3, 1, 1, 3
        self.horizontalLayout_10.addLayout(self.gridLayout)
        #将self.horizontalLayout_10增加的布局self.gridLayout
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        #将self.verticalLayout_4增加的布局self.horizontalLayout_10

        self.retranslateUi(Dialog)
        #将self.verticalLayout_2增加的小部件设为self.label
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #响应信号Dialog
        #connectSlotsByName是响应信号的函数

    def retranslateUi(self, Dialog):
        #设定retranslateUi函数
        _translate = QtCore.QCoreApplication.translate
        #将QtCore.QCoreApplication.translate的对象self.widget赋值给_translate
        #通过查询已安装的翻译文件，返回sourceText的翻译文本
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        #将窗口标题设为Dialog
        self.label.setText(_translate("Dialog", "           登录"))
        #将self.label显示文本设为登录
        self.label_2.setText(_translate("Dialog", "账号"))
        #将self.label_2显示文本设为账号
        self.label_3.setText(_translate("Dialog", "密码"))
        #将self.label_3显示文本设为密码
        self.pushButton.setText(_translate("Dialog", "登录"))
        #将self.pushButton显示文本设为登录
        self.pushButton_2.setText(_translate("Dialog", "注册"))
        #将self.pushButton_2显示文本设为注册
        self.label_4.setText(_translate("Dialog", "             注册"))
        #将self.label_4显示文本设为注册
        self.label_5.setText(_translate("Dialog", "用户名"))
        #将self.label_5显示文本设为用户名
        self.label_9.setText(_translate("Dialog", "性别"))
        #将self.label_9显示文本设为性别
        self.radioButton.setText(_translate("Dialog", "男"))
        #将self.radioButton显示文本设为男
        self.radioButton_2.setText(_translate("Dialog", "女"))
        #将self.radioButton_2显示文本设为女
        self.label_6.setText(_translate("Dialog", "设置密码"))
        #将self.label_6显示文本设为设置密码
        self.label_7.setText(_translate("Dialog", "验证密码"))
        #将self.label_7显示文本设为验证密码
        self.label_8.setText(_translate("Dialog", "电子邮箱"))
        #将self.label_8显示文本设为电子邮箱
        self.checkBox_2.setText(_translate("Dialog", "开启骚扰邮件"))
        #将self.checkBox_2显示文本设为开启骚扰邮件
        self.checkBox.setText(_translate("Dialog", "已阅读《霸王条款》"))
        #将self.checkBox显示文本设为已阅读《霸王条款》
        self.pushButton_3.setText(_translate("Dialog", "注册"))
        #将self.pushButton_3显示文本设为注册
        self.pushButton_17.setText(_translate("Dialog", "Del"))
        #将self.pushButton_17显示文本设为Del
        self.pushButton_12.setText(_translate("Dialog", "7"))
        #将self.pushButton_12显示文本设为7
        self.pushButton_4.setText(_translate("Dialog", "1"))
        #将self.pushButton_4显示文本设为1
        self.pushButton_5.setText(_translate("Dialog", "2"))
        #将self.pushButton_5显示文本设为2
        self.pushButton_10.setText(_translate("Dialog", "6"))
        #将self.pushButton_10显示文本设为6
        self.pushButton_6.setText(_translate("Dialog", "3"))
        #将self.pushButton_6显示文本设为3
        self.pushButton_7.setText(_translate("Dialog", "+"))
        #将self.pushButton_7显示文本设为+
        self.pushButton_9.setText(_translate("Dialog", "5"))
        #将self.pushButton_9显示文本设为5
        self.pushButton_16.setText(_translate("Dialog", "0"))
        #将self.pushButton_16显示文本设为0
        self.pushButton_11.setText(_translate("Dialog", "-"))
        #将self.pushButton_11显示文本设为-
        self.pushButton_8.setText(_translate("Dialog", "4"))
        #将self.pushButton_8显示文本设为4
        self.pushButton_14.setText(_translate("Dialog", "9"))
        #将self.pushButton_14显示文本设为9
        self.pushButton_15.setText(_translate("Dialog", "*"))
        #将self.pushButton_15显示文本设为*
        self.pushButton_19.setText(_translate("Dialog", "/"))
        #将self.pushButton_19显示文本设为/
        self.pushButton_13.setText(_translate("Dialog", "8"))
        #将self.pushButton_13显示文本设为8


if __name__ == "__main__":
#判断当前运行的是否为自己的模块
    import sys
    #引入sys模块
    app = QtWidgets.QApplication(sys.argv)
    #将本文件定义为应用app
    Dialog = QtWidgets.QDialog()
    #将QtWidgets.QLabel的对象self.widget赋值给self.label
    ui = Ui_Dialog
    #设ui为Ui_Dialog
    ui.setupUi(Dialog)
    #ui设置用户接口为Dialog
    Dialog.show()
    #显示窗口Dialog
    sys.exit(app.exec_())
    #循环app的主程序直到不再调用.exit
